version: '3.8'

services:
  # nginx reverse proxy - serves frontend and proxies to backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - classroom-network

  # Express backend server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - "3001"
    networks:
      - classroom-network

networks:
  classroom-network:
    driver: bridge