version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=staging
      - VITE_SERVER_URL=${VITE_SERVER_URL:-http://localhost:3001}
    depends_on:
      - backend
    networks:
      - classroom-widgets-staging

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=staging
      - PORT=3001
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost}
    networks:
      - classroom-widgets-staging

networks:
  classroom-widgets-staging:
    driver: bridge