import fs from 'fs';
const S = '/tmp/claude-0/-home-user-classroom-widgets/1019d9be-4c14-5465-b2e2-1ffcd8946341/scratchpad';
const r2 = JSON.parse(fs.readFileSync(`${S}/r2g-args.json`, 'utf8'));

// Keep the real-app reference block, surfaces and colour sections from round 2; replace the lessons.
const base = r2.brief.split('## Lessons from 81 evaluator verdicts')[0];

const brief = `${base}## ROUND 3 — what 162 evaluator verdicts taught us (binding)
Round-2 winner, unanimous (first place with all nine evaluators): "Rainbow Countdown" — the app's cream timer face inside a thick round-capped rainbow ring, depleted so a pale spent gap shows at upper-left, a big bold 5 on the face, white die-cut rim, amber plate. Glyph: a bold 5 inside a 260° C-ring. Read its contact sheet: ${S}/sheets/r2-ring.png, and the round-2 overview ${S}/sheets/r2-overview.png.
Why it won: one centred hero that fits the 80% maskable circle (PWA/Android crops), survives true 16px, and its glyph is the icon with colour removed. Why others lost: collages of several widgets (timer + card + sticker + confetti) crowd the plate edges, clip under circular masks and turn to mush at 16px; pictorial glyphs (full-body hamster, star, heart) blob at tray size.
Fix these in every concept:
- ONE centred hero inside the 80% circle; at most one small supporting accent.
- Glyph = ONE solid tone. No 50% opacity anywhere (it reads as a disabled menu item). Draw it as a sign with a closed outline, SF Symbols weight — not a shrunken illustration. Must hold at TRUE 1x 16px on a 100%-scaling school PC.
- Look-alikes to avoid: SF Symbols goforward.5 / gobackward.5 (a digit inside an open arc with an arrowhead-like cap — keep caps round, never arrow-shaped), a refresh/reload arrow, the letter G or C, Google One's numeral-in-multicolour-ring, a glowing AI halo (smooth rainbow halos now read as "AI feature"). A clearly segmented or clearly flat ring helps.
- Numeral: use 5 (never 4).
- Low-poly facets vanish below 64px and look dated: at most two or three large flat facets, and none in the small master. If an amber plate sits on the app's own amber canvas it needs a cream outline to separate.
- Deliver a real macOS DARK appearance variant and a hand-tuned SMALL master (16–32px: flat, fewer segments, heavier strokes).
- The runner creatures are the app's most ownable asset; the in-app hamster/fox/tortoise/bee/penguin/pip SVG markup (24-unit viewBox, -12..12) is in /home/user/classroom-widgets/design/icon-exploration/reference/timer-creatures.json — reuse the app's own drawing style if you draw one.
- Optional but valued: describe a live menu-bar state (the ring emptying as a timer runs) in your concept text.

## Non-negotiables
- Colour icon, dark icon, small master and glyph are ONE mark. Glyph: viewBox 0 0 1024 1024, #000 fills only, one solid tone, no gradients/filters/opacity; strokes only as stroke="#000" fill="none".
- Icons: viewBox 0 0 1024 1024, self-contained, no text except the single numeral.
- CRITICAL: prefix ids — icon "{{SLUG}}-", iconDark "{{SLUG}}d-", iconSmall "{{SLUG}}s-", glyph "{{SLUG}}g-".`;

const directions = [
  { slug: 'master', title: 'The master ring — Rainbow Countdown, refined', brief: `Take the round-2 winner to final quality. Keep the composition (cream face, round-capped rainbow ring with the spent gap, bold 5, white die-cut rim) and fix every note: caps round and clearly not arrowheads (kill the goforward.5 read), ring colours deepened so it reads as an object not a glowing halo, plate reduced to two or three flat amber facets (or a clean amber gradient), all inside the 80% circle. This is the "safe excellent" option — make it impeccable at every size.` },
  { slug: 'hamcap', title: 'Ring + the hamster riding the leading cap', brief: `The panel's favourite merge: the master ring with the app's own hamster (drawn in the in-app creature style — see timer-creatures.json) small, about a sixth of the ring's diameter, riding the ring's leading end exactly where the app runs it. The numeral stays the hero; the hamster is the signature. Glyph: the C-ring + 5, with a round two-eared bump fused onto the leading cap (the hamster reduced to head and ears) — that bump is what kills the skip-5 look-alike and makes it ownable.` },
  { slug: 'starcap', title: 'Ring + a gold star sticker in the spent gap', brief: `The master ring with ONE small die-cut gold star sticker (the app's own sticker style: chunky, thick white border, slight tilt) sitting in the spent gap of the ring — a "well done" wink that fills the gap and makes the C-shape unambiguous. Star small (~20% of ring diameter), numeral still the hero. Glyph: C-ring + 5 + a solid star in the gap, separated by ≥100-unit knockouts.` },
  { slug: 'segments', title: 'Segmented rainbow dial', brief: `Answer the "AI halo / Google One" risk: the ring rebuilt as 6–8 chunky round-ended segments in rainbow order (like coloured dial blocks), with the last one or two segments missing as the spent time. Flat, graphic, toy-like, unmistakably a countdown and not a glow. Numeral 5 in the face. Glyph: the segmented arc as solid blocks around the 5 — must stay crisp at 16px (fewer, bigger segments if needed, ≥100-unit gaps).` },
  { slug: 'brandring', title: 'The ring in the brand palette', brief: `The calm continuity option: the same ring composition, but the arc coloured in the brand family (deep sage → sage → terracotta → dusty rose) instead of a full rainbow, on a cream-to-pale-sage plate like the currently shipping icon — or on deep sage with a cream face. It must still be recognisably the app's timer. For a client who liked the original grid's calm palette. Glyph identical in construction to the master ring.` },
  { slug: 'mascot', title: 'The hamster as the hero', brief: `The most ownable and daring option: the runner creature IS the logo. The app's hamster (in-app style, timer-creatures.json), big and centred, peeking over or running along a short thick arc of the rainbow ring. Charming, instantly "ours", and a character the brand can use everywhere. Glyph: head-only — a round two-eared hamster head (eye knocked out) sitting on a thick arc; must read at true 16px. Show that the colour icon and glyph are the same idea even though the glyph is simplified.` },
  { slug: 'reel', title: 'The randomiser reel — a timer-free alternative', brief: `Keep a non-timer option alive for the final choice: the randomiser as a vertical reel — a cream card with the purple→pink→amber window, three stacked name pills cropped by the window, the middle one solid white and bold, neighbours half-hidden; at most two small paper confetti flecks. Centred and large (≥70% of the plate width), no corner placement. Glyph: a framed vertical stack of three pills, the middle solid, the outer ones drawn as outlines (no opacity) — must read as "pick one", not a battery or toaster.` },
  { slug: 'ringplus', title: 'Hero ring with a supporting widget strip', brief: `The "Widgets, plural" story without a collage: the master ring takes two-thirds of the plate as the clear hero, and a small vertical traffic-light pill (dark pill, three lamps) tucks against its lower-right, overlapping the ring slightly. Everything inside the 80% circle. Glyph: C-ring + 5 with a small solid pill (three knocked-out dots, or a notch) fused at the lower-right — not two unrelated objects.` },
  { slug: 'diecut', title: 'The ring as a die-cut sticker', brief: `Brand-system option: the whole mark treated as one of the app's stickers — the rainbow timer ring + face as a sticker with a thick white die-cut outline and a soft shadow, lifted slightly off a flat amber (or deep sage) plate, tilted a few degrees. The die-cut outline becomes the brand's style for web, docs and marketing. Glyph: the sticker's closed outer outline with the C-ring and 5 inside as knockouts.` },
];

fs.writeFileSync(`${S}/r3-args.json`, JSON.stringify({ round: 3, brief, directions }));
console.log(directions.map(d => d.slug).join(', '), brief.length);
