// Widget type constants
export const WIDGET_TYPES = {
  RANDOMISER: 0,
  TIMER: 1,
  LIST: 2,
  TASK_CUE: 3,
  TRAFFIC_LIGHT: 4,
  SOUND_MONITOR: 5,
  LINK_SHORTENER: 6,
  TEXT_BANNER: 7,
  IMAGE_DISPLAY: 8,
  SOUND_EFFECTS: 9,
  STAMP: 10,
  POLL: 11,
  QRCODE: 12,
  DATA_SHARE: 13,
  VISUALISER: 14,
  RT_FEEDBACK: 15
};