/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "voice_commands.baml": "// BAML schema for parsing voice commands\n// This provides type-safe LLM-powered command extraction\n\n// Define the command output structure\nclass VoiceCommand {\n  action string @description(\"The action to perform (e.g., CREATE_TIMER, RESET_TIMER, RANDOMISE)\")\n  target string @description(\"The widget target (e.g., timer, randomiser, list, poll)\")\n  confidence float @description(\"Confidence score from 0.0 to 1.0\")\n  parameters CommandParameters? @description(\"Optional parameters for the command\")\n  feedback FeedbackMessage @description(\"Feedback message for the user\")\n}\n\nclass CommandParameters {\n  duration int? @description(\"Duration in seconds for timer commands\")\n  items string[]? @description(\"List of items for list widget\")\n  text string? @description(\"Text content for banner widget\")\n  soundName string? @description(\"Sound effect name\")\n  mode string? @description(\"Work mode for task cue\")\n  state string? @description(\"Traffic light state\")\n  options string[]? @description(\"Poll options\")\n}\n\nclass FeedbackMessage {\n  message string @description(\"Human-readable feedback message\")\n  type string @description(\"Message type: success or error\")\n  shouldSpeak bool @description(\"Whether to use text-to-speech\")\n}\n\n// Main function for parsing voice commands\nfunction ParseVoiceCommand(transcript: string) -> VoiceCommand {\n  client OllamaClient\n\n  prompt #\"\n    You are a voice command parser for a classroom widget application.\n    Parse the following voice command: \"{{ transcript }}\"\n\n    Extract the action, target widget, parameters, and confidence (0.8-0.95 for clear commands).\n    Provide a helpful feedback message.\n  \"#\n}\n\n// Client configuration for Ollama\nclient OllamaClient {\n  provider ollama\n  options {\n    model \"llama2\"\n    base_url \"http://localhost:11434\"\n  }\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}