/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CommandParameters,  FeedbackMessage,  VoiceCommand } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CommandParameters {
      duration?: number | null
      items?: string[] | null
      text?: string | null
      soundName?: string | null
      mode?: string | null
      state?: string | null
      options?: string[] | null
    }
    export interface FeedbackMessage {
      message?: string | null
      type?: string | null
      shouldSpeak?: boolean | null
    }
    export interface VoiceCommand {
      action?: string | null
      target?: string | null
      confidence?: number | null
      parameters?: CommandParameters | null
      feedback?: FeedbackMessage | null
    }
}